global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OTel Collector를 통해 들어오는 Biomni 에이전트 메트릭 추가
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.178.0.11:9100', '10.178.0.12:9100', '10.178.0.13:9100']